### ISSUE TITLE
Incompatibility with PrisonLabor and RepairingPriority namespace bug?

### ISSUE THREAD

**Issue by jagerguy36** [emipa606/CleaningPriority#7]
1) Currently Prisoners Cannot do Cleaning with this mod enabled. Changing the condition check should fix this issue:

in WorkGiver_CleanFilthPrioritized.cs line 31 (in HasJobOnThing)
Change if (pawn.Faction != Faction.OfPlayer) to if (pawn.Faction != Faction.OfPlayer && !pawn.IsPrisoner)

2) It seems RepairingPriority namepace is wrongly included in the [latest commit](https://github.com/emipa606/CleaningPriority/commit/1f5e9eb87e446206922adc55f37db311d4981f11#diff-6616b749212e660b8a6af2a4d08ba60cd05dfb22dbce816ffa6ac16aba9f97e7). See
CleaningManager_MapComponent.cs line 7 and 100

I would have made a merge request myself, but It seems the project is using syntax that my assembler cannot recognize for C# 
e.g.)
private List<Area> addableAreas = []; instead of private List<Area> addableAreas = new();

So I was unsure as to what kind of setup you have for building this project, and decided to just report the issue.

Thank you always for your amazing works. You are truly the hero we all love.

**Comment by emipa606** [comment]
Thanks for the detailed report, should be fixed in a38e9ba
Namespace was due to me mixing up two open solutions, sorry about that!

Regarding the C# syntax, it was added in C# language version 12. Makes for nicer array/list creations:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/arrays and
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/collections
